services:
  - type: web
    name: autoanalyst-ai
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "cd AutoAnalyst && gunicorn AutoAnalyst.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
