import io
import base64
import datetime
import re

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm, mm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    Image as RLImage, HRFlowable, PageBreak, KeepTogether,
)
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.pdfgen import canvas as pdfcanvas


def _clean_html(text):
    return re.sub(r'<[^>]+>', '', str(text))


# ── Strict Black & White palette ──────────────────────────────────────────────
BLACK    = colors.HexColor('#0a0a0a')
DARK     = colors.HexColor('#1a1a1a')
GRAY_D   = colors.HexColor('#3a3a3a')
GRAY_M   = colors.HexColor('#6b6b6b')
GRAY_L   = colors.HexColor('#a8a8a8')
GRAY_LT  = colors.HexColor('#d4d4d4')
GRAY_BG  = colors.HexColor('#f0f0f0')
GRAY_BG2 = colors.HexColor('#f7f7f7')
WHITE    = colors.white
BORDER   = colors.HexColor('#c8c8c8')


W, H = A4
L_MAR = R_MAR = 2.2 * cm
T_MAR = 2.5 * cm
B_MAR = 2.5 * cm
CONTENT_W = W - L_MAR - R_MAR


# ── Page decorations ──────────────────────────────────────────────────────────
def _draw_cover(c, doc):
    # Top black band
    c.setFillColor(BLACK)
    c.rect(0, H - 6.5*cm, W, 6.5*cm, fill=1, stroke=0)
    # Thin rule below band
    c.setFillColor(GRAY_L)
    c.rect(0, H - 6.5*cm - 0.06*cm, W, 0.06*cm, fill=1, stroke=0)
    # Bottom bar
    c.setFillColor(GRAY_BG)
    c.rect(0, 0, W, 2.2*cm, fill=1, stroke=0)
    c.setFillColor(GRAY_M)
    c.setFont('Times-Roman', 8)
    c.drawCentredString(W/2, 1.1*cm, 'Generated by AutoAnalyst AI  |  Confidential')
    c.setFillColor(GRAY_L)
    c.rect(L_MAR, 2.2*cm, CONTENT_W, 0.04*cm, fill=1, stroke=0)


def _draw_later(c, doc):
    # Header rule
    c.setFillColor(BLACK)
    c.rect(L_MAR, H - 1.4*cm, CONTENT_W, 0.06*cm, fill=1, stroke=0)
    # Header text
    c.setFillColor(BLACK)
    c.setFont('Times-Bold', 8.5)
    c.drawString(L_MAR, H - 1.2*cm, 'AutoAnalyst AI — ML Analysis Report')
    c.setFillColor(GRAY_M)
    c.setFont('Times-Roman', 8)
    c.drawRightString(W - R_MAR, H - 1.2*cm,
                      datetime.datetime.now().strftime('%B %d, %Y'))
    # Footer rule + page number
    c.setFillColor(GRAY_L)
    c.rect(L_MAR, 1.6*cm, CONTENT_W, 0.04*cm, fill=1, stroke=0)
    c.setFillColor(GRAY_M)
    c.setFont('Times-Roman', 8)
    c.drawRightString(W - R_MAR, 1.2*cm, f'Page {doc.page}')
    c.drawString(L_MAR, 1.2*cm, 'Machine Learning Pipeline Report')


# ── Helper builders ───────────────────────────────────────────────────────────
def _sp(n=10):
    return Spacer(1, n)


def _hr(color=BORDER, thick=0.5):
    return HRFlowable(width='100%', thickness=thick, color=color,
                      spaceAfter=4, spaceBefore=4)


def _section_header(number, title, story):
    label = f'{number}. {title}' if number else title
    t = Table(
        [[Paragraph(f'<b>{label}</b>',
                    ParagraphStyle('SH', fontSize=12, leading=15,
                                   fontName='Times-Bold', textColor=WHITE,
                                   alignment=TA_LEFT))]],
        colWidths=[CONTENT_W],
    )
    t.setStyle(TableStyle([
        ('BACKGROUND',    (0, 0), (-1, -1), BLACK),
        ('LEFTPADDING',   (0, 0), (-1, -1), 12),
        ('RIGHTPADDING',  (0, 0), (-1, -1), 12),
        ('TOPPADDING',    (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(KeepTogether([_sp(16), t, _sp(10)]))


def _sub_header(title, story):
    t = Table(
        [[Paragraph(f'<b>{title}</b>',
                    ParagraphStyle('SubH', fontSize=10, leading=13,
                                   fontName='Times-Bold', textColor=BLACK))]],
        colWidths=[CONTENT_W],
    )
    t.setStyle(TableStyle([
        ('BACKGROUND',    (0, 0), (-1, -1), GRAY_BG),
        ('LEFTPADDING',   (0, 0), (-1, -1), 10),
        ('TOPPADDING',    (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LINEBELOW',     (0, 0), (-1, -1), 1.2, BLACK),
    ]))
    story.append(KeepTogether([_sp(10), t, _sp(6)]))


def _body_style():
    return ParagraphStyle('Bod', fontSize=10, leading=15,
                           textColor=DARK, fontName='Times-Roman', spaceAfter=4)


def _muted_style():
    return ParagraphStyle('Mut', fontSize=8.5, leading=12,
                           textColor=GRAY_M, fontName='Times-Roman',
                           alignment=TA_CENTER)


def _table_style(header_bg=BLACK, alt=True):
    styles = [
        ('BACKGROUND',    (0, 0), (-1, 0),  header_bg),
        ('TEXTCOLOR',     (0, 0), (-1, 0),  WHITE),
        ('FONTNAME',      (0, 0), (-1, 0),  'Times-Bold'),
        ('FONTNAME',      (0, 1), (-1, -1), 'Times-Roman'),
        ('FONTSIZE',      (0, 0), (-1, -1), 9),
        ('LEADING',       (0, 0), (-1, -1), 13),
        ('GRID',          (0, 0), (-1, -1), 0.4, BORDER),
        ('LEFTPADDING',   (0, 0), (-1, -1), 8),
        ('RIGHTPADDING',  (0, 0), (-1, -1), 8),
        ('TOPPADDING',    (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('VALIGN',        (0, 0), (-1, -1), 'MIDDLE'),
    ]
    if alt:
        styles.append(('ROWBACKGROUNDS', (0, 1), (-1, -1), [GRAY_BG2, WHITE]))
    return TableStyle(styles)


def _add_chart(story, b64_str, caption='', width_cm=14.5, height_ratio=0.58):
    try:
        img_bytes = io.BytesIO(base64.b64decode(b64_str))
        w = width_cm * cm
        h = w * height_ratio
        img = RLImage(img_bytes, width=w, height=h)
        card = Table([[img]], colWidths=[CONTENT_W])
        card.setStyle(TableStyle([
            ('ALIGN',         (0, 0), (-1, -1), 'CENTER'),
            ('VALIGN',        (0, 0), (-1, -1), 'MIDDLE'),
            ('BOX',           (0, 0), (-1, -1), 0.6, GRAY_L),
            ('BACKGROUND',    (0, 0), (-1, -1), WHITE),
            ('TOPPADDING',    (0, 0), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ]))
        story.append(card)
        if caption:
            story.append(_sp(4))
            story.append(Paragraph(caption, _muted_style()))
        story.append(_sp(12))
    except Exception:
        pass


# ── Main generator ────────────────────────────────────────────────────────────
def generate_pdf_report(meta: dict, dataset_name: str, ml_results: list,
                        charts_data: dict, feature_importance: list,
                        insights: list) -> bytes:

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=L_MAR, rightMargin=R_MAR,
        topMargin=T_MAR + 0.5*cm, bottomMargin=B_MAR + 0.5*cm,
        title='AutoAnalyst AI — ML Analysis Report',
        author='AutoAnalyst AI',
    )

    body  = _body_style()
    muted = _muted_style()
    story = []
    pre   = meta.get('preprocessing', {})
    now   = datetime.datetime.now().strftime('%B %d, %Y')
    p_type = meta.get('problem_type', 'classification')

    # ══════════════════════════════════════════════════════════════════════════
    # COVER PAGE
    # ══════════════════════════════════════════════════════════════════════════
    story.append(_sp(75))

    story.append(Paragraph('Machine Learning Analysis Report',
                            ParagraphStyle('CL', fontSize=11, leading=14,
                                           textColor=GRAY_L, fontName='Times-Roman',
                                           alignment=TA_CENTER)))
    story.append(_sp(6))
    story.append(Paragraph('Automated ML Pipeline',
                            ParagraphStyle('CT', fontSize=30, leading=36,
                                           textColor=WHITE, fontName='Times-Bold',
                                           alignment=TA_CENTER)))
    story.append(_sp(8))
    story.append(Paragraph('AutoAnalyst AI',
                            ParagraphStyle('CA', fontSize=12, leading=16,
                                           textColor=GRAY_L, fontName='Times-Italic',
                                           alignment=TA_CENTER)))
    story.append(_sp(45))

    cover_data = [
        ['Dataset',       dataset_name],
        ['Target Column', meta.get('target', 'N/A')],
        ['Problem Type',  meta.get('problem_type', 'N/A').title()],
        ['Best Model',    meta.get('best_model_name', 'N/A')],
        [meta.get('metric_label', 'Score'), f"{meta.get('best_score', 'N/A')}%"],
        ['Report Date',   now],
    ]
    tm = Table(cover_data, colWidths=[4.5*cm, 10*cm], hAlign='CENTER')
    tm.setStyle(TableStyle([
        ('FONTNAME',      (0, 0), (0, -1),  'Times-Bold'),
        ('FONTNAME',      (1, 0), (1, -1),  'Times-Roman'),
        ('FONTSIZE',      (0, 0), (-1, -1), 10),
        ('LEADING',       (0, 0), (-1, -1), 15),
        ('TEXTCOLOR',     (0, 0), (0, -1),  GRAY_L),
        ('TEXTCOLOR',     (1, 0), (1, -1),  GRAY_BG),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING',    (0, 0), (-1, -1), 8),
        ('LINEBELOW',     (0, 0), (-1, -2), 0.3, GRAY_D),
        ('LEFTPADDING',   (0, 0), (-1, -1), 0),
    ]))
    story.append(tm)
    story.append(PageBreak())

    # ══════════════════════════════════════════════════════════════════════════
    # ABSTRACT / EXECUTIVE SUMMARY
    # ══════════════════════════════════════════════════════════════════════════
    _section_header('', 'Executive Summary', story)

    story.append(Paragraph(
        f'This report presents the results of an automated machine learning pipeline '
        f'applied to the dataset <b>{dataset_name}</b>. The objective was to predict '
        f'the target variable <b>"{meta.get("target", "")}"</b> using a '
        f'<b>{p_type}</b> approach. '
        f'After data cleaning and preprocessing, <b>{pre.get("rows_after_clean", "?")} rows</b> '
        f'and <b>{(pre.get("cols_after", 1) - 1)} features</b> were used for training. '
        f'Multiple models were evaluated and the best-performing model was '
        f'<b>{meta.get("best_model_name", "")}</b>, achieving '
        f'<b>{meta.get("best_score", "?")}%</b> {meta.get("metric_label", "score")} '
        f'on the held-out test set.',
        body))
    story.append(_sp(10))

    # Summary metrics table
    summary_data = [
        ['Metric', 'Value'],
        ['Dataset', dataset_name],
        ['Total Rows (original)', str(pre.get('original_rows', 'N/A'))],
        ['Rows after Cleaning', str(pre.get('rows_after_clean', 'N/A'))],
        ['Features Used', str((pre.get('cols_after', 1) - 1) if isinstance(pre.get('cols_after'), int) else 'N/A')],
        ['Training Samples', str(pre.get('n_train', 'N/A'))],
        ['Test Samples', str(pre.get('n_test', 'N/A'))],
        ['Problem Type', p_type.title()],
        ['Best Model', meta.get('best_model_name', 'N/A')],
        [meta.get('metric_label', 'Score'), f"{meta.get('best_score', 'N/A')}%"],
    ]
    extra = meta.get('extra_metrics', {})
    for k, v in extra.items():
        summary_data.append([k, f'{v}%' if isinstance(v, float) and v > 1 else str(v)])

    st = Table(summary_data, colWidths=[7*cm, CONTENT_W - 7*cm])
    st.setStyle(_table_style())
    story.append(st)
    story.append(PageBreak())

    # ══════════════════════════════════════════════════════════════════════════
    # SECTION 1 — DATASET OVERVIEW
    # ══════════════════════════════════════════════════════════════════════════
    _section_header(1, 'Dataset Overview', story)

    ov_data = [
        ['Property', 'Value', 'Notes'],
        ['Original Rows',       str(pre.get('original_rows', 'N/A')),    'Total records in the uploaded file'],
        ['Original Columns',    str(pre.get('original_cols', 'N/A')),    'Including the target column'],
        ['Duplicate Rows',      str(pre.get('duplicates_count', 'N/A')), 'Identical rows detected and removed'],
        ['Rows After Cleaning', str(pre.get('rows_after_clean', 'N/A')), 'After removing null-target rows'],
        ['Rows Dropped',        str(pre.get('rows_dropped', 'N/A')),     'Rows removed due to missing target'],
        ['Columns Used',        str(pre.get('cols_after', 'N/A')),       'Post-feature-selection (incl. target)'],
        ['Training Samples',    str(pre.get('n_train', 'N/A')),          '80% split, random_state=42'],
        ['Test Samples',        str(pre.get('n_test', 'N/A')),           '20% held-out for evaluation'],
    ]
    ov_t = Table(ov_data, colWidths=[4.5*cm, 3*cm, CONTENT_W - 7.5*cm])
    ov_t.setStyle(_table_style())
    story.append(ov_t)

    dropped = pre.get('cols_dropped', [])
    if dropped:
        _sub_header(f'Auto-Dropped Columns ({len(dropped)})', story)
        dc_data = [['#', 'Column Name', 'Reason']]
        for i, col in enumerate(dropped, 1):
            dc_data.append([str(i), col, '>80% missing / constant / ID-like'])
        dc_t = Table(dc_data, colWidths=[1*cm, 7*cm, CONTENT_W - 8*cm])
        dc_t.setStyle(_table_style(header_bg=GRAY_D))
        story.append(dc_t)

    # ══════════════════════════════════════════════════════════════════════════
    # SECTION 2 — DATA QUALITY
    # ══════════════════════════════════════════════════════════════════════════
    _section_header(2, 'Data Quality & Missing Values', story)
    null_info = pre.get('null_info', {})
    if null_info:
        story.append(Paragraph(
            f'<b>{len(null_info)}</b> column(s) contained missing values. '
            'Numeric columns: Median imputation. Categorical columns: Mode imputation.',
            body))
        story.append(_sp(8))
        mv_data = [['Column', 'Data Type', 'Missing #', 'Missing %', 'Strategy']]
        for col, info in null_info.items():
            dtype_str = info.get('dtype', 'N/A')
            strategy = 'Median' if ('int' in dtype_str or 'float' in dtype_str) else 'Mode'
            mv_data.append([col, dtype_str, str(info.get('count', 0)),
                             f"{info.get('pct', 0)}%", strategy])
        mv_t = Table(mv_data, colWidths=[4.5*cm, 2.5*cm, 2*cm, 2*cm, CONTENT_W - 11*cm])
        mv_t.setStyle(_table_style())
        story.append(mv_t)
    else:
        ok_t = Table([['No missing values were detected in this dataset.']],
                     colWidths=[CONTENT_W])
        ok_t.setStyle(TableStyle([
            ('BACKGROUND',    (0, 0), (-1, -1), GRAY_BG),
            ('TEXTCOLOR',     (0, 0), (-1, -1), DARK),
            ('FONTNAME',      (0, 0), (-1, -1), 'Times-Bold'),
            ('FONTSIZE',      (0, 0), (-1, -1), 10),
            ('LEFTPADDING',   (0, 0), (-1, -1), 14),
            ('TOPPADDING',    (0, 0), (-1, -1), 12),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ('BOX',           (0, 0), (-1, -1), 0.6, BLACK),
        ]))
        story.append(ok_t)

    story.append(PageBreak())

    # ══════════════════════════════════════════════════════════════════════════
    # SECTION 3 — FEATURE ENGINEERING
    # ══════════════════════════════════════════════════════════════════════════
    _section_header(3, 'Feature Engineering & Encoding', story)
    feature_names = meta.get('feature_names', [])
    lm = meta.get('label_mappings', {})
    story.append(Paragraph(
        f'<b>{len(feature_names)}</b> feature(s) were used for training. '
        'All numeric features were standardised using <b>StandardScaler</b> '
        '(mean = 0, std = 1). Categorical columns were converted to numeric '
        'values using <b>Label Encoding</b> prior to scaling.',
        body))
    story.append(_sp(8))
    feat_data = [['#', 'Feature Name', 'Type', 'Processing Applied']]
    for i, feat in enumerate(feature_names, 1):
        feat_type = 'Categorical' if feat in lm else 'Numeric'
        enc = 'Label Encoding → StandardScaler' if feat in lm else 'StandardScaler'
        feat_data.append([str(i), feat, feat_type, enc])
    feat_t = Table(feat_data, colWidths=[1*cm, 7*cm, 3*cm, CONTENT_W - 11*cm])
    feat_t.setStyle(_table_style())
    story.append(feat_t)

    # ══════════════════════════════════════════════════════════════════════════
    # SECTION 4 — MODEL TRAINING & SELECTION
    # ══════════════════════════════════════════════════════════════════════════
    _section_header(4, 'Model Training & Selection', story)
    story.append(Paragraph(
        f'Problem type: <b>{p_type.title()}</b>. '
        f'Model selection criterion: <b>{meta.get("metric_label", "Score")}</b> on 20% test set. '
        'All models were trained using default hyperparameters. '
        'The model achieving the highest test score was selected as the best model.',
        body))
    story.append(_sp(8))

    if ml_results:
        best_name = meta.get('best_model_name', '')
        sorted_results = sorted(ml_results, key=lambda x: x['score'], reverse=True)
        r_data = [['Rank', 'Model Name', f'{meta.get("metric_label", "Score")} (%)', 'Result']]
        for i, r in enumerate(sorted_results, 1):
            is_best = r['name'] == best_name
            r_data.append([str(i), r['name'], f"{r['score']}%",
                            'Best Model' if is_best else '—'])
        r_t = Table(r_data, colWidths=[1.5*cm, 8*cm, 3.5*cm, CONTENT_W - 13*cm])
        ts = _table_style()
        for i, r in enumerate(sorted_results, 1):
            if r['name'] == best_name:
                ts.add('BACKGROUND', (0, i), (-1, i), GRAY_BG)
                ts.add('TEXTCOLOR',  (0, i), (-1, i), BLACK)
                ts.add('FONTNAME',   (0, i), (-1, i), 'Times-Bold')
        r_t.setStyle(ts)
        story.append(r_t)

    story.append(PageBreak())

    # ══════════════════════════════════════════════════════════════════════════
    # SECTION 5 — VISUAL ANALYSIS (Charts)
    # ══════════════════════════════════════════════════════════════════════════
    if charts_data:
        _section_header(5, 'Visual Analysis', story)

        if 'model_comparison' in charts_data:
            _sub_header('Model Performance Comparison', story)
            story.append(Paragraph(
                f'The bar chart below compares all trained models by '
                f'{meta.get("metric_label", "score")} on the test set. '
                f'The best-performing model is highlighted.',
                body))
            story.append(_sp(6))
            _add_chart(story, charts_data['model_comparison'],
                       f'Figure 1: All trained models ranked by {meta.get("metric_label","Score")} (%)',
                       width_cm=14.5, height_ratio=0.52)

        if 'feature_importance' in charts_data:
            _sub_header('Feature Importance', story)
            story.append(Paragraph(
                'The following chart shows the importance score of each feature '
                'as determined by the best model. Higher scores indicate greater '
                'influence on model predictions.',
                body))
            story.append(_sp(6))
            _add_chart(story, charts_data['feature_importance'],
                       'Figure 2: Top features ranked by importance score',
                       width_cm=14.5, height_ratio=0.52)

        if 'confusion' in charts_data:
            _sub_header('Confusion Matrix', story)
            story.append(Paragraph(
                'The confusion matrix shows the counts of true vs. predicted labels '
                'on the held-out test set. Diagonal cells represent correct predictions.',
                body))
            story.append(_sp(6))
            _add_chart(story, charts_data['confusion'],
                       'Figure 3: Confusion matrix on held-out test set',
                       width_cm=10, height_ratio=0.85)

        if 'actual_vs_pred' in charts_data:
            _sub_header('Actual vs Predicted', story)
            story.append(Paragraph(
                'The scatter plot compares actual target values against model predictions. '
                'Points close to the diagonal line indicate accurate predictions.',
                body))
            story.append(_sp(6))
            _add_chart(story, charts_data['actual_vs_pred'],
                       'Figure 4: Actual vs predicted values on test set',
                       width_cm=12, height_ratio=0.72)

        story.append(PageBreak())

    # ══════════════════════════════════════════════════════════════════════════
    # SECTION 6 — FEATURE IMPORTANCE TABLE
    # ══════════════════════════════════════════════════════════════════════════
    sec = 6
    if feature_importance:
        _section_header(sec, 'Feature Importance Rankings', story)
        story.append(Paragraph(
            'The table below lists features in descending order of importance. '
            'Relative strength is shown as a percentage of the top feature score.',
            body))
        story.append(_sp(8))
        max_imp = feature_importance[0]['importance'] if feature_importance else 1
        fi_data = [['Rank', 'Feature Name', 'Score', 'Relative Strength (%)']]
        for i, item in enumerate(feature_importance, 1):
            pct = round(item['importance'] / max_imp * 100, 1)
            fi_data.append([str(i), item['feature'],
                             f"{item['importance']:.4f}", f'{pct}%'])
        fi_t = Table(fi_data, colWidths=[1.5*cm, 8*cm, 3*cm, CONTENT_W - 12.5*cm])
        fi_t.setStyle(_table_style())
        story.append(fi_t)
        story.append(PageBreak())
        sec += 1

    # ══════════════════════════════════════════════════════════════════════════
    # SECTION 7 — INSIGHTS & RECOMMENDATIONS
    # ══════════════════════════════════════════════════════════════════════════
    _section_header(sec, 'Insights & Recommendations', story)
    if insights:
        _sub_header('Auto-Generated Insights', story)
        for ins in insights:
            row = Table(
                [[Paragraph(f'\u2022  {_clean_html(ins)}', body)]],
                colWidths=[CONTENT_W])
            row.setStyle(TableStyle([
                ('LEFTPADDING',   (0, 0), (-1, -1), 10),
                ('TOPPADDING',    (0, 0), (-1, -1), 4),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
                ('LINEBELOW',     (0, 0), (-1, -1), 0.3, GRAY_LT),
            ]))
            story.append(row)
        story.append(_sp(12))

    _sub_header('Recommendations', story)
    recs = [
        'Collect more labelled samples if the score is below expectation.',
        'Apply Recursive Feature Elimination (RFE) to reduce noise from weak features.',
        'Tune model hyperparameters using GridSearchCV or RandomizedSearchCV.',
        'Use k-fold cross-validation for a more robust performance estimate.',
        'If class imbalance exists, consider SMOTE oversampling or class_weight="balanced".',
        'Retrain periodically as new data becomes available (model drift prevention).',
    ]
    rec_data = [[Paragraph(f'{i+1}.  {r}',
                           ParagraphStyle('Rec', fontSize=10, leading=15,
                                          textColor=DARK, fontName='Times-Roman'))]
                for i, r in enumerate(recs)]
    rec_t = Table(rec_data, colWidths=[CONTENT_W])
    rec_t.setStyle(TableStyle([
        ('LEFTPADDING',    (0, 0), (-1, -1), 10),
        ('TOPPADDING',     (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING',  (0, 0), (-1, -1), 5),
        ('ROWBACKGROUNDS', (0, 0), (-1, -1), [GRAY_BG2, WHITE]),
        ('BOX',            (0, 0), (-1, -1), 0.5, BORDER),
        ('GRID',           (0, 0), (-1, -1), 0.3, GRAY_LT),
    ]))
    story.append(rec_t)

    story.append(_sp(20))
    story.append(_hr(BLACK, 0.8))
    story.append(_sp(6))
    story.append(Paragraph(
        f'Report generated on {now} by AutoAnalyst AI. For academic and internal use only.',
        ParagraphStyle('Footer', fontSize=8.5, leading=12, textColor=GRAY_M,
                       fontName='Times-Italic', alignment=TA_CENTER)))

    doc.build(story, onFirstPage=_draw_cover, onLaterPages=_draw_later)
    return buf.getvalue()
