import io
import base64
import datetime
import re

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm, mm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    Image as RLImage, HRFlowable, PageBreak, KeepTogether,
)
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.pdfgen import canvas as pdfcanvas


def _clean_html(text):
    return re.sub(r'<[^>]+>', '', str(text))


# ── Color palette ─────────────────────────────────────────────────────────────
PRIMARY   = colors.HexColor('#1e293b')   # dark slate-blue
ACCENT    = colors.HexColor('#16a34a')   # green
AMBER     = colors.HexColor('#b45309')
RED_C     = colors.HexColor('#dc2626')
MUTED     = colors.HexColor('#64748b')
MUTED2    = colors.HexColor('#94a3b8')
BORDER    = colors.HexColor('#e2e8f0')
BG_ALT    = colors.HexColor('#f8fafc')
BG_DARK   = colors.HexColor('#f1f5f9')
WHITE     = colors.white
BLACK     = colors.HexColor('#0f172a')
BLUE_LITE = colors.HexColor('#dbeafe')
GREEN_LITE= colors.HexColor('#dcfce7')
AMBER_LITE= colors.HexColor('#fef3c7')


W, H = A4
L_MAR = R_MAR = 2.0 * cm
T_MAR = 2.2 * cm
B_MAR = 2.2 * cm
CONTENT_W = W - L_MAR - R_MAR


# ── Page decorations ──────────────────────────────────────────────────────────
def _draw_cover(c, doc):
    """Full cover background + decorative elements."""
    # Dark top banner
    c.setFillColor(PRIMARY)
    c.rect(0, H - 7.5*cm, W, 7.5*cm, fill=1, stroke=0)

    # Green accent strip
    c.setFillColor(ACCENT)
    c.rect(0, H - 7.5*cm, W, 0.35*cm, fill=1, stroke=0)

    # Light bottom stripe
    c.setFillColor(BG_ALT)
    c.rect(0, 0, W, 2.8*cm, fill=1, stroke=0)

    # Bottom text
    c.setFillColor(MUTED)
    c.setFont('Helvetica', 7.5)
    c.drawCentredString(W/2, 1.3*cm, 'Generated by AutoAnalyst AI  ·  Confidential')


def _draw_later(c, doc):
    """Header + footer on every non-cover page."""
    # Top thin line
    c.setFillColor(PRIMARY)
    c.rect(L_MAR, H - 1.3*cm, CONTENT_W, 0.04*cm, fill=1, stroke=0)

    # Header: left brand, right date
    c.setFillColor(PRIMARY)
    c.setFont('Helvetica-Bold', 8)
    c.drawString(L_MAR, H - 1.1*cm, 'AutoAnalyst AI')
    c.setFillColor(MUTED)
    c.setFont('Helvetica', 7.5)
    c.drawRightString(W - R_MAR, H - 1.1*cm,
                      datetime.datetime.now().strftime('%B %d, %Y'))

    # Bottom line + page number
    c.setFillColor(BORDER)
    c.rect(L_MAR, 1.4*cm, CONTENT_W, 0.04*cm, fill=1, stroke=0)
    c.setFillColor(MUTED)
    c.setFont('Helvetica', 7.5)
    c.drawRightString(W - R_MAR, 1.05*cm, f'Page {doc.page}')
    c.drawString(L_MAR, 1.05*cm, 'ML Pipeline Report')


# ── Helper builders ───────────────────────────────────────────────────────────
def _sp(n=10):
    return Spacer(1, n)

def _hr(color=BORDER, thick=0.5):
    return HRFlowable(width='100%', thickness=thick, color=color,
                      spaceAfter=5, spaceBefore=3)

def _section_header(number, title, story):
    """Styled section header with colored left bar (simulated via table)."""
    t = Table(
        [[Paragraph(f'<font color="white"><b>{number}. {title}</b></font>',
                    ParagraphStyle('SH', fontSize=11, leading=14,
                                   fontName='Helvetica-Bold', textColor=WHITE))]],
        colWidths=[CONTENT_W],
    )
    t.setStyle(TableStyle([
        ('BACKGROUND',    (0,0), (-1,-1), PRIMARY),
        ('LEFTPADDING',   (0,0), (-1,-1), 10),
        ('RIGHTPADDING',  (0,0), (-1,-1), 10),
        ('TOPPADDING',    (0,0), (-1,-1), 7),
        ('BOTTOMPADDING', (0,0), (-1,-1), 7),
        ('ROUNDEDCORNERS', [3]),
    ]))
    story.append(KeepTogether([_sp(14), t, _sp(8)]))

def _sub_header(title, story):
    t = Table(
        [[Paragraph(f'<b>{title}</b>',
                    ParagraphStyle('SubH', fontSize=9.5, leading=13,
                                   fontName='Helvetica-Bold', textColor=PRIMARY))]],
        colWidths=[CONTENT_W],
    )
    t.setStyle(TableStyle([
        ('BACKGROUND',    (0,0), (-1,-1), BG_DARK),
        ('LEFTPADDING',   (0,0), (-1,-1), 8),
        ('TOPPADDING',    (0,0), (-1,-1), 5),
        ('BOTTOMPADDING', (0,0), (-1,-1), 5),
        ('LINEBELOW',     (0,0), (-1,-1), 1.5, ACCENT),
    ]))
    story.append(KeepTogether([_sp(8), t, _sp(5)]))

def _body_style():
    return ParagraphStyle('Bod', fontSize=8.5, leading=13,
                           textColor=colors.HexColor('#334155'),
                           fontName='Helvetica', spaceAfter=3)

def _muted_style():
    return ParagraphStyle('Mut', fontSize=7.5, leading=11,
                           textColor=MUTED, fontName='Helvetica')

def _table_style(hdr_color=PRIMARY, alt=True):
    styles = [
        ('BACKGROUND',    (0, 0), (-1, 0),  hdr_color),
        ('TEXTCOLOR',     (0, 0), (-1, 0),  WHITE),
        ('FONTNAME',      (0, 0), (-1, 0),  'Helvetica-Bold'),
        ('FONTSIZE',      (0, 0), (-1, -1), 8),
        ('LEADING',       (0, 0), (-1, -1), 11),
        ('GRID',          (0, 0), (-1, -1), 0.3, BORDER),
        ('LEFTPADDING',   (0, 0), (-1, -1), 7),
        ('RIGHTPADDING',  (0, 0), (-1, -1), 7),
        ('TOPPADDING',    (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('VALIGN',        (0, 0), (-1, -1), 'MIDDLE'),
    ]
    if alt:
        styles.append(('ROWBACKGROUNDS', (0, 1), (-1, -1), [BG_ALT, WHITE]))
    return TableStyle(styles)

def _add_chart(story, b64_str, caption='', width_cm=14.5, height_ratio=0.58):
    try:
        img_bytes = io.BytesIO(base64.b64decode(b64_str))
        w = width_cm * cm
        h = w * height_ratio
        img = RLImage(img_bytes, width=w, height=h)

        # wrap in a thin-bordered table for a card feel
        card = Table([[img]], colWidths=[CONTENT_W])
        card.setStyle(TableStyle([
            ('ALIGN',         (0,0), (-1,-1), 'CENTER'),
            ('VALIGN',        (0,0), (-1,-1), 'MIDDLE'),
            ('BOX',           (0,0), (-1,-1), 0.5, BORDER),
            ('BACKGROUND',    (0,0), (-1,-1), WHITE),
            ('TOPPADDING',    (0,0), (-1,-1), 6),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ]))
        story.append(card)
        if caption:
            story.append(Paragraph(caption, _muted_style()))
        story.append(_sp(10))
    except Exception:
        pass

def _metric_cards(data):
    """data = [(label, value, bg_color), ...]  — returns a Table."""
    n = len(data)
    col_w = CONTENT_W / n
    header_row = []
    value_row  = []
    for label, val, bg in data:
        header_row.append(
            Paragraph(label, ParagraphStyle('ML', fontSize=7, leading=9,
                                            fontName='Helvetica-Bold',
                                            textColor=WHITE, alignment=TA_CENTER))
        )
        value_row.append(
            Paragraph(str(val), ParagraphStyle('MV', fontSize=16, leading=20,
                                               fontName='Helvetica-Bold',
                                               textColor=WHITE, alignment=TA_CENTER))
        )
    t = Table([header_row, value_row], colWidths=[col_w]*n)
    style = [
        ('TOPPADDING',    (0,0), (-1,-1), 8),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ('LEFTPADDING',   (0,0), (-1,-1), 4),
        ('RIGHTPADDING',  (0,0), (-1,-1), 4),
        ('VALIGN',        (0,0), (-1,-1), 'MIDDLE'),
        ('INNERGRID',     (0,0), (-1,-1), 0.5, colors.HexColor('#ffffff40')),
        ('BOX',           (0,0), (-1,-1), 0, WHITE),
    ]
    for i, (_, _, bg) in enumerate(data):
        style.append(('BACKGROUND', (i,0), (i,-1), bg))
    t.setStyle(TableStyle(style))
    return t


# ── Main generator ────────────────────────────────────────────────────────────
def generate_pdf_report(meta: dict, dataset_name: str, ml_results: list,
                        charts_data: dict, feature_importance: list,
                        insights: list) -> bytes:

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=L_MAR, rightMargin=R_MAR,
        topMargin=T_MAR + 0.4*cm, bottomMargin=B_MAR + 0.4*cm,
        title='AutoAnalyst AI — ML Report',
        author='AutoAnalyst AI',
    )

    body  = _body_style()
    muted = _muted_style()
    story = []
    pre   = meta.get('preprocessing', {})
    now   = datetime.datetime.now().strftime('%B %d, %Y')

    # ══════════════════════════════════════════════════════════════════════════
    # COVER PAGE
    # ══════════════════════════════════════════════════════════════════════════
    story.append(_sp(80))  # push below dark banner

    story.append(Paragraph('Machine Learning', ParagraphStyle(
        'CL', fontSize=13, leading=16, textColor=colors.HexColor('#94a3b8'),
        fontName='Helvetica', alignment=TA_CENTER)))
    story.append(_sp(4))
    story.append(Paragraph('Pipeline Report', ParagraphStyle(
        'CT', fontSize=32, leading=36, textColor=WHITE,
        fontName='Helvetica-Bold', alignment=TA_CENTER)))
    story.append(_sp(6))
    story.append(Paragraph('AutoAnalyst AI', ParagraphStyle(
        'CA', fontSize=11, leading=14, textColor=colors.HexColor('#7dd3fc'),
        fontName='Helvetica-Bold', alignment=TA_CENTER)))

    story.append(_sp(40))

    # Cover summary table
    cover_data = [
        ['Dataset',       dataset_name],
        ['Target Column', meta.get('target', 'N/A')],
        ['Problem Type',  meta.get('problem_type', 'N/A').title()],
        ['Best Model',    meta.get('best_model_name', 'N/A')],
        [meta.get('metric_label', 'Score'), f"{meta.get('best_score', 'N/A')}%"],
        ['Report Date',   now],
    ]
    tm = Table(cover_data, colWidths=[4.5*cm, 10*cm], hAlign='CENTER')
    tm.setStyle(TableStyle([
        ('FONTNAME',      (0,0), (0,-1),  'Helvetica-Bold'),
        ('FONTNAME',      (1,0), (1,-1),  'Helvetica'),
        ('FONTSIZE',      (0,0), (-1,-1), 9.5),
        ('LEADING',       (0,0), (-1,-1), 14),
        ('TEXTCOLOR',     (0,0), (0,-1),  colors.HexColor('#94a3b8')),
        ('TEXTCOLOR',     (1,0), (1,-1),  colors.HexColor('#e2e8f0')),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ('TOPPADDING',    (0,0), (-1,-1), 8),
        ('LINEBELOW',     (0,0), (-1,-2), 0.3, colors.HexColor('#334155')),
        ('LEFTPADDING',   (0,0), (-1,-1), 0),
    ]))
    story.append(tm)
    story.append(PageBreak())

    # ══════════════════════════════════════════════════════════════════════════
    # PAGE 2 — EXECUTIVE SUMMARY (metric cards)
    # ══════════════════════════════════════════════════════════════════════════
    _section_header('', 'Executive Summary', story)

    card_data = [
        ('Original Rows',    pre.get('original_rows', '—'),  PRIMARY),
        ('After Cleaning',   pre.get('rows_after_clean', '—'), colors.HexColor('#155e75')),
        ('Features Used',    pre.get('cols_after', '—') - 1
                             if isinstance(pre.get('cols_after'), int) else '—',
                             colors.HexColor('#166534')),
        ('Best Score',       f"{meta.get('best_score', '—')}%", ACCENT),
    ]
    story.append(_metric_cards(card_data))
    story.append(_sp(14))

    # quick summary paragraph
    p_type = meta.get('problem_type', 'classification')
    story.append(Paragraph(
        f'A <b>{p_type}</b> pipeline was trained on <b>{dataset_name}</b> '
        f'to predict the target column <b>"{meta.get("target","")}"</b>. '
        f'After cleaning, <b>{pre.get("rows_after_clean","?")} rows</b> and '
        f'<b>{(pre.get("cols_after",1)-1)} features</b> were used. '
        f'The best-performing model was <b>{meta.get("best_model_name","")}</b> '
        f'achieving <b>{meta.get("best_score","?")}%</b> '
        f'{meta.get("metric_label","score")} on the held-out test set.',
        body))

    story.append(_sp(12))

    # Key metrics side-by-side table
    extra = meta.get('extra_metrics', {})
    if extra:
        _sub_header('Best Model — Additional Metrics', story)
        em_rows = [['Metric', 'Value']]
        for k, v in extra.items():
            em_rows.append([k, f'{v}%' if isinstance(v, float) and v > 1 else str(v)])
        em_t = Table(em_rows, colWidths=[9*cm, CONTENT_W - 9*cm])
        em_t.setStyle(_table_style())
        story.append(em_t)

    story.append(PageBreak())

    # ══════════════════════════════════════════════════════════════════════════
    # PAGE 3 — DATASET OVERVIEW
    # ══════════════════════════════════════════════════════════════════════════
    _section_header(1, 'Dataset Overview', story)

    ov_data = [
        ['Property', 'Value', 'Notes'],
        ['Original Rows',       str(pre.get('original_rows', 'N/A')),    'Total records uploaded'],
        ['Original Columns',    str(pre.get('original_cols', 'N/A')),    'Including target column'],
        ['Duplicate Rows',      str(pre.get('duplicates_count', 'N/A')), 'Identical rows removed'],
        ['Rows After Cleaning', str(pre.get('rows_after_clean', 'N/A')), 'After null-target removal'],
        ['Rows Dropped',        str(pre.get('rows_dropped', 'N/A')),     'Missing target rows'],
        ['Columns Used',        str(pre.get('cols_after', 'N/A')),       'Post-feature selection (incl. target)'],
        ['Training Samples',    str(pre.get('n_train', 'N/A')),          '80 % split (seed = 42)'],
        ['Test Samples',        str(pre.get('n_test',  'N/A')),          '20 % held-out evaluation'],
    ]
    ov_t = Table(ov_data, colWidths=[4.5*cm, 3*cm, CONTENT_W - 7.5*cm])
    ov_t.setStyle(_table_style())
    story.append(ov_t)

    dropped = pre.get('cols_dropped', [])
    if dropped:
        _sub_header(f'Auto-Dropped Columns ({len(dropped)})', story)
        dc_data = [['#', 'Column Name', 'Reason']]
        for i, col in enumerate(dropped, 1):
            dc_data.append([str(i), col, '>80 % missing / constant / identifier'])
        dc_t = Table(dc_data, colWidths=[1*cm, 7*cm, CONTENT_W - 8*cm])
        dc_t.setStyle(_table_style(hdr_color=AMBER))
        story.append(dc_t)

    # ── Data Quality ───────────────────────────────────────────────────────
    _section_header(2, 'Data Quality & Missing Values', story)
    null_info = pre.get('null_info', {})
    if null_info:
        story.append(Paragraph(
            f'<b>{len(null_info)}</b> column(s) contained missing values. '
            'Numeric columns → Median imputation. Categorical columns → Mode imputation.',
            body))
        story.append(_sp(6))
        mv_data = [['Column', 'Dtype', 'Missing #', 'Missing %', 'Strategy']]
        for col, info in null_info.items():
            dtype_str = info.get('dtype', 'N/A')
            strategy = 'Median' if ('int' in dtype_str or 'float' in dtype_str) else 'Mode'
            mv_data.append([col, dtype_str,
                             str(info.get('count', 0)),
                             f"{info.get('pct', 0)}%", strategy])
        mv_t = Table(mv_data, colWidths=[4.5*cm, 2.5*cm, 2*cm, 2*cm, CONTENT_W - 11*cm])
        mv_t.setStyle(_table_style(hdr_color=colors.HexColor('#0c4a6e')))
        story.append(mv_t)
    else:
        ok_t = Table([['✓  No missing values detected in this dataset.']],
                     colWidths=[CONTENT_W])
        ok_t.setStyle(TableStyle([
            ('BACKGROUND',    (0,0), (-1,-1), GREEN_LITE),
            ('TEXTCOLOR',     (0,0), (-1,-1), colors.HexColor('#14532d')),
            ('FONTNAME',      (0,0), (-1,-1), 'Helvetica-Bold'),
            ('FONTSIZE',      (0,0), (-1,-1), 9),
            ('LEFTPADDING',   (0,0), (-1,-1), 12),
            ('TOPPADDING',    (0,0), (-1,-1), 10),
            ('BOTTOMPADDING', (0,0), (-1,-1), 10),
            ('BOX',           (0,0), (-1,-1), 0.5, ACCENT),
        ]))
        story.append(ok_t)

    story.append(PageBreak())

    # ══════════════════════════════════════════════════════════════════════════
    # PAGE 4 — FEATURES & MODEL RESULTS
    # ══════════════════════════════════════════════════════════════════════════
    _section_header(3, 'Feature Engineering & Encoding', story)
    feature_names  = meta.get('feature_names', [])
    lm             = meta.get('label_mappings', {})
    story.append(Paragraph(
        f'<b>{len(feature_names)}</b> feature(s) used for training. '
        'All features standardised with <b>StandardScaler</b>. '
        'Categorical columns converted via <b>Label Encoding</b> first.',
        body))
    story.append(_sp(6))
    feat_data = [['#', 'Feature', 'Type', 'Processing']]
    for i, feat in enumerate(feature_names, 1):
        feat_type = 'Categorical' if feat in lm else 'Numeric'
        enc = 'Label Enc → StandardScaler' if feat in lm else 'StandardScaler only'
        feat_data.append([str(i), feat, feat_type, enc])
    feat_t = Table(feat_data, colWidths=[1*cm, 7*cm, 3*cm, CONTENT_W - 11*cm])
    feat_t.setStyle(_table_style())
    story.append(feat_t)

    _section_header(4, 'Model Training & Selection', story)
    story.append(Paragraph(
        f'Problem type: <b>{p_type.title()}</b>. '
        f'Selection metric: <b>{meta.get("metric_label","Score")}</b> on 20 % test set. '
        'All models trained with default hyperparameters.',
        body))
    story.append(_sp(6))
    if ml_results:
        best_name = meta.get('best_model_name', '')
        sorted_results = sorted(ml_results, key=lambda x: x['score'], reverse=True)
        r_data = [['Rank', 'Model', f'{meta.get("metric_label","Score")} (%)', 'Status']]
        for i, r in enumerate(sorted_results, 1):
            is_best = r['name'] == best_name
            r_data.append([
                str(i), r['name'], f"{r['score']}%",
                '★ Best' if is_best else '—',
            ])
        r_t = Table(r_data, colWidths=[1.5*cm, 8*cm, 3.5*cm, CONTENT_W - 13*cm])
        ts = _table_style()
        # Highlight best row
        for i, r in enumerate(sorted_results, 1):
            if r['name'] == best_name:
                ts.add('BACKGROUND', (0, i), (-1, i), GREEN_LITE)
                ts.add('TEXTCOLOR',  (0, i), (-1, i), colors.HexColor('#14532d'))
                ts.add('FONTNAME',   (0, i), (-1, i), 'Helvetica-Bold')
        story.append(r_t)

    story.append(PageBreak())

    # ══════════════════════════════════════════════════════════════════════════
    # PAGE 5 — VISUAL ANALYSIS
    # ══════════════════════════════════════════════════════════════════════════
    if charts_data:
        _section_header(5, 'Visual Analysis', story)

        if 'model_comparison' in charts_data:
            _sub_header('Model Performance Comparison', story)
            _add_chart(story, charts_data['model_comparison'],
                       f'All models ranked by {meta.get("metric_label","Score")}',
                       width_cm=14.5, height_ratio=0.52)

        if 'feature_importance' in charts_data:
            _sub_header('Feature Importance', story)
            _add_chart(story, charts_data['feature_importance'],
                       'Top features by importance score (best model)',
                       width_cm=14.5, height_ratio=0.52)

        if 'confusion' in charts_data:
            _sub_header('Confusion Matrix', story)
            _add_chart(story, charts_data['confusion'],
                       'Confusion matrix on held-out test set',
                       width_cm=10, height_ratio=0.82)

        if 'actual_vs_pred' in charts_data:
            _sub_header('Actual vs Predicted', story)
            _add_chart(story, charts_data['actual_vs_pred'],
                       'Scatter: actual vs predicted values on test set',
                       width_cm=12, height_ratio=0.72)

        story.append(PageBreak())

    # ══════════════════════════════════════════════════════════════════════════
    # PAGE 6 — FEATURE IMPORTANCE TABLE
    # ══════════════════════════════════════════════════════════════════════════
    sec = 6
    if feature_importance:
        _section_header(sec, 'Feature Importance Rankings', story)
        max_imp = feature_importance[0]['importance'] if feature_importance else 1
        fi_data = [['Rank', 'Feature', 'Score', 'Relative Strength']]
        for i, item in enumerate(feature_importance, 1):
            pct  = round(item['importance'] / max_imp * 100, 1)
            bars = '█' * int(pct / 8) + '░' * (12 - int(pct / 8))
            fi_data.append([str(i), item['feature'], f"{item['importance']:.4f}",
                             f'{bars}  {pct}%'])
        fi_t = Table(fi_data, colWidths=[1.5*cm, 7*cm, 3*cm, CONTENT_W - 11.5*cm])
        fi_t.setStyle(_table_style())
        story.append(fi_t)
        story.append(PageBreak())
        sec += 1

    # ══════════════════════════════════════════════════════════════════════════
    # FINAL PAGE — INSIGHTS & RECOMMENDATIONS
    # ══════════════════════════════════════════════════════════════════════════
    _section_header(sec, 'Auto-Generated Insights', story)
    if insights:
        for ins in insights:
            row = Table([[Paragraph(f'• {_clean_html(ins)}', body)]],
                        colWidths=[CONTENT_W])
            row.setStyle(TableStyle([
                ('LEFTPADDING',   (0,0), (-1,-1), 10),
                ('TOPPADDING',    (0,0), (-1,-1), 3),
                ('BOTTOMPADDING', (0,0), (-1,-1), 3),
                ('LINEBELOW',     (0,0), (-1,-1), 0.3, BORDER),
            ]))
            story.append(row)
        story.append(_sp(12))
    else:
        story.append(Paragraph('No insights generated.', muted))

    _sub_header('Recommendations', story)
    recs = [
        ('Collect more labelled data if accuracy is below expectation.', PRIMARY),
        ('Apply Recursive Feature Elimination to reduce noise features.', PRIMARY),
        ('Tune hyperparameters with GridSearchCV / RandomizedSearchCV.', PRIMARY),
        ('Use k-fold cross-validation for a more robust performance estimate.', PRIMARY),
        ('If class imbalance exists, consider SMOTE or class_weight="balanced".', AMBER),
        ('Retrain periodically as new data arrives (model drift prevention).', PRIMARY),
    ]
    rec_data = [[
        Paragraph(f'→  {text}',
                  ParagraphStyle('Rec', fontSize=8.5, leading=12,
                                 textColor=col, fontName='Helvetica'))
    ] for text, col in recs]
    rec_t = Table(rec_data, colWidths=[CONTENT_W])
    rec_t.setStyle(TableStyle([
        ('LEFTPADDING',   (0,0), (-1,-1), 10),
        ('TOPPADDING',    (0,0), (-1,-1), 4),
        ('BOTTOMPADDING', (0,0), (-1,-1), 4),
        ('ROWBACKGROUNDS',(0,0), (-1,-1), [BG_ALT, WHITE]),
        ('BOX',           (0,0), (-1,-1), 0.4, BORDER),
    ]))
    story.append(rec_t)

    story.append(_sp(18))
    story.append(_hr(PRIMARY, 0.8))
    story.append(Paragraph(
        f'Report generated on {now} by AutoAnalyst AI  ·  For internal use only.',
        ParagraphStyle('Footer', fontSize=7.5, leading=10, textColor=MUTED,
                       fontName='Helvetica', alignment=TA_CENTER)))

    # ── Build ─────────────────────────────────────────────────────────────────
    doc.build(story, onFirstPage=_draw_cover, onLaterPages=_draw_later)
    return buf.getvalue()
