# Generated by Django 5.2.15 on 2026-06-06 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('rows', models.IntegerField(default=0)),
                ('columns', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(blank=True, max_length=255)),
                ('target_column', models.CharField(max_length=255)),
                ('problem_type', models.CharField(max_length=50)),
                ('best_model_name', models.CharField(max_length=255)),
                ('best_score', models.FloatField()),
                ('metric_label', models.CharField(max_length=50)),
                ('n_features', models.IntegerField(default=0)),
                ('n_train', models.IntegerField(default=0)),
                ('n_test', models.IntegerField(default=0)),
                ('all_results', models.JSONField(default=list)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_runs', to='dashboard.dataset')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=255)),
                ('target_column', models.CharField(blank=True, max_length=255)),
                ('result_value', models.CharField(max_length=500)),
                ('input_summary', models.JSONField(default=dict)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
                ('training_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='dashboard.trainingrun')),
            ],
            options={
                'ordering': ['-predicted_at'],
            },
        ),
    ]
