import json
import textwrap


def _md_cell(source: str) -> dict:
    return {
        "cell_type": "markdown",
        "id": f"md-{abs(hash(source[:30])) % 10**8}",
        "metadata": {},
        "source": source,
    }


def _code_cell(source: str) -> dict:
    return {
        "cell_type": "code",
        "id": f"code-{abs(hash(source[:30])) % 10**8}",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source,
    }


def generate_notebook(meta: dict, dataset_name: str) -> str:
    problem_type    = meta.get('problem_type', 'classification')
    target          = meta.get('target', 'target')
    best_model_name = meta.get('best_model_name', 'Random Forest')
    metric_label    = meta.get('metric_label', 'Accuracy')
    best_score      = meta.get('best_score', 0)
    feature_names   = meta.get('feature_names', [])
    label_mappings  = meta.get('label_mappings', {})
    pre             = meta.get('preprocessing', {})
    encoded_cols    = pre.get('encoded_cols', [])

    clf_map = {
        'Logistic Regression':    'LogisticRegression(max_iter=2000, random_state=42)',
        'Random Forest':          'RandomForestClassifier(n_estimators=100, random_state=42)',
        'K-Nearest Neighbors':    'KNeighborsClassifier(n_neighbors=5)',
        'Support Vector Machine': 'SVC(random_state=42)',
    }
    reg_map = {
        'Linear Regression':       'LinearRegression()',
        'Random Forest Regressor': 'RandomForestRegressor(n_estimators=100, random_state=42)',
        'Ridge Regression':        'Ridge()',
    }
    model_init = (clf_map if problem_type == 'classification' else reg_map).get(
        best_model_name, 'RandomForestClassifier(n_estimators=100, random_state=42)'
    )

    imports_clf = textwrap.dedent("""\
        from sklearn.linear_model import LogisticRegression, Ridge, LinearRegression
        from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
        from sklearn.neighbors import KNeighborsClassifier
        from sklearn.svm import SVC
        from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
        import seaborn as sns""")

    imports_reg = textwrap.dedent("""\
        from sklearn.linear_model import LinearRegression, Ridge
        from sklearn.ensemble import RandomForestRegressor
        from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
        import matplotlib.pyplot as plt""")

    enc_cols_repr   = repr(encoded_cols)
    feat_names_repr = repr(feature_names)

    eval_clf = textwrap.dedent(f"""\
        preds = model.predict(X_test)
        acc   = accuracy_score(y_test, preds)
        print(f"Accuracy: {{acc*100:.2f}}%")
        print()
        print(classification_report(y_test, preds))
        cm = confusion_matrix(y_test, preds)
        plt.figure(figsize=(6, 4))
        sns.heatmap(cm, annot=True, fmt='d', cmap='Greys')
        plt.title('Confusion Matrix'); plt.xlabel('Predicted'); plt.ylabel('Actual')
        plt.tight_layout(); plt.show()""")

    eval_reg = textwrap.dedent(f"""\
        preds = model.predict(X_test)
        r2  = r2_score(y_test, preds)
        mse = mean_squared_error(y_test, preds)
        mae = mean_absolute_error(y_test, preds)
        print(f"R²   : {{r2*100:.2f}}%")
        print(f"MSE  : {{mse:.4f}}")
        print(f"MAE  : {{mae:.4f}}")
        print(f"RMSE : {{mse**0.5:.4f}}")
        plt.figure(figsize=(6, 4))
        plt.scatter(y_test, preds, alpha=0.5, color='#18181b', s=20)
        mn, mx = min(y_test.min(), preds.min()), max(y_test.max(), preds.max())
        plt.plot([mn, mx], [mn, mx], 'r--', label='Perfect fit')
        plt.xlabel('Actual'); plt.ylabel('Predicted'); plt.title('Actual vs Predicted')
        plt.legend(); plt.tight_layout(); plt.show()""")

    feature_comments = '\n'.join(
        f'    "{f}": 0,  # '
        + (f'categorical — e.g. {label_mappings[f][:3]}' if f in label_mappings else 'numeric')
        for f in feature_names
    )

    cells = [
        _md_cell(f"""\
# AutoAnalyst AI — Machine Learning Notebook
**Dataset:** `{dataset_name}`  
**Target:** `{target}`  
**Problem Type:** {problem_type.title()}  
**Best Model:** {best_model_name}  
**{metric_label}:** {best_score}%

---
Auto-generated by **AutoAnalyst AI**. Reproduces the complete ML pipeline end-to-end.
"""),
        _md_cell("## 1. Imports"),
        _code_cell(f"""\
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
{imports_clf if problem_type == 'classification' else imports_reg}

print("Libraries loaded.")
"""),
        _md_cell("## 2. Load Dataset"),
        _code_cell(f"""\
df = pd.read_csv("{dataset_name}")   # or pd.read_excel(...)
print(f"Shape: {{df.shape[0]}} rows × {{df.shape[1]}} columns")
df.head(10)
"""),
        _md_cell("## 3. Exploratory Data Analysis"),
        _code_cell(f"""\
print("=== Missing Values ===")
missing = df.isnull().sum()
print(missing[missing > 0].to_string() or "None")
print(f"\\n=== Duplicates: {{df.duplicated().sum()}} ===")
print("\\n=== Types ===")
print(df.dtypes.to_string())
print("\\n=== Summary ===")
df.describe(include='all')
"""),
        _md_cell("## 4. Preprocessing"),
        _code_cell(f"""\
TARGET = "{target}"
df = df.dropna(subset=[TARGET])

SKIP_COLS = ['id', 'index', 'row', 'no', 'num', 'uuid', 'email', 'phone', 'name']
cols_to_drop = [
    col for col in df.columns if col != TARGET and (
        df[col].isna().mean() > 0.80 or
        df[col].nunique() <= 1 or
        col.lower() in SKIP_COLS
    )
]
if cols_to_drop:
    print(f"Dropping: {{cols_to_drop}}")
    df = df.drop(columns=cols_to_drop)

for col in df.columns:
    if df[col].isna().any():
        if pd.api.types.is_numeric_dtype(df[col]):
            df[col] = df[col].fillna(df[col].median())
        else:
            df[col] = df[col].fillna(df[col].mode().iloc[0])

encoders = {{}}
label_mappings = {{}}
for col in df.columns:
    if not pd.api.types.is_numeric_dtype(df[col]):
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col].astype(str))
        encoders[col] = le
        label_mappings[col] = list(le.classes_)

for col in df.columns:
    df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0)

FEATURE_NAMES = {feat_names_repr}
X = df[FEATURE_NAMES].astype(float)
y = df[TARGET]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42)
print(f"Train: {{len(X_train)}}, Test: {{len(X_test)}}")
"""),
        _md_cell(f"## 5. Train — {best_model_name}"),
        _code_cell(f"""\
model = {model_init}
model.fit(X_train, y_train)
print(f"Trained: {{type(model).__name__}}")
"""),
        _md_cell("## 6. Evaluate"),
        _code_cell(eval_clf if problem_type == 'classification' else eval_reg),
        _md_cell("## 7. Feature Importance"),
        _code_cell(f"""\
feature_names = {feat_names_repr}
if hasattr(model, 'feature_importances_'):
    importances = model.feature_importances_
elif hasattr(model, 'coef_'):
    importances = np.abs(model.coef_).flatten()[:len(feature_names)]
else:
    importances = None

if importances is not None:
    fi_df = pd.DataFrame({{'Feature': feature_names, 'Importance': importances}})
    fi_df = fi_df.sort_values('Importance', ascending=False).reset_index(drop=True)
    print(fi_df.to_string(index=False))
    plt.figure(figsize=(8, max(4, len(feature_names) * 0.4)))
    plt.barh(fi_df['Feature'][::-1], fi_df['Importance'][::-1], color='#18181b')
    plt.xlabel('Importance'); plt.title('Feature Importance')
    plt.tight_layout(); plt.show()
"""),
        _md_cell("## 8. Predict New Sample"),
        _code_cell(f"""\
new_sample = {{
{feature_comments}
}}
sample_arr = scaler.transform(pd.DataFrame([new_sample])[feature_names].astype(float))
prediction = model.predict(sample_arr)[0]

label_mappings_local = {repr(label_mappings)}
target_lm = label_mappings_local.get("{target}")
if target_lm is not None:
    try:
        prediction_label = target_lm[int(prediction)]
    except Exception:
        prediction_label = str(prediction)
else:
    prediction_label = str(prediction)

print(f"Predicted {target}: {{prediction_label}}")
"""),
        _md_cell("## 9. Save & Load Model"),
        _code_cell(f"""\
import joblib
joblib.dump({{
    'model':          model,
    'scaler':         scaler,
    'encoders':       encoders,
    'label_mappings': label_mappings,
    'feature_names':  feature_names,
    'problem_type':   '{problem_type}',
    'target':         '{target}',
}}, 'best_model.joblib')
print("Saved to best_model.joblib")
"""),
    ]

    notebook = {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.11.0"},
        },
        "cells": cells,
    }
    return json.dumps(notebook, indent=2, ensure_ascii=False)
